name: rkbin-patcher

on:
  push:
    branches:
      - main



jobs:
    patch-builder:
        runs-on: ubuntu-latest
        
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                push: true
                build-args:
                  COMMIT=7c35e21a8529b3758d1f051d1a5dc62aae934b2b
                tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
